accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.SignUpView.as_view(), name='signup'),
]

tsurami/urls.py
from django.urls import path
from . import views

app_name = 'tsurami'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.MyListView.as_view(), name='index'),
]

tsurami_prj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tsurami.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from tsurami.models import Note

# Create your models here.

class User(AbstractUser):
    """カスタムユーザ"""
    aka     = models.CharField(max_length=40, verbose_name="二つ名")
    notes   = models.ManyToManyField(Note, verbose_name='ノート')

tsurami/models.py
import uuid
from django.db import models
from django.utils import timezone

class NoteManager(models.Manager):
    def create_note(self, title):
        note = self.create(title=title)
        return note

class Note(models.Model):
    """発言の集合"""
    note_id     = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at  = models.DateTimeField('created-date', default=timezone.now)
    title       = models.CharField('text', max_length=40, blank=False)
    # created_by  = models.IntegerField(blank=False)

    objects = NoteManager()

    def post(self):
        pass

    def __str__(self):
        return(self.title)

class PageManager(models.Manager):
    def create_page(self, text, note):
        page = self.create(text=text, note=note)
        return page

class Page(models.Model):
    """発言"""
    page_id     = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at  = models.DateTimeField('created-at', default=timezone.now)
    text        = models.CharField('text', max_length=300, blank=False)
    note        = models.ForeignKey(
        Note,
        on_delete=models.CASCADE,
    )

    objects = PageManager()

    def __str__(self):
        return str(self.page_id)

accounts/forms.py
from django import forms
# from django.contrib.auth.forms import (
#     AuthenticationForm, UserCreationForm, PasswordChangeForm,
#     PasswordResetForm, SetPasswordForm
# )
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from tsurami.models import Note

User = get_user_model()

class UserSignUpForm(UserCreationForm):
    """Sign-up form"""

    class Meta:
        model = User
        # if User.USERNAME_FIELD == 'email':
        #     fields = ('email',)
        # else:
        #     fields = ('username', 'email')

        # required fields for signup
        fields = ('username', 'email', 'aka')

    def save(self, commit=True):
        user = super().save(commit=False)

        # Save prior to create relations
        if commit:
            user.save()

            # Automatically create your first Note
            note = Note.objects.create_note("new note for " + user.username)
            user.notes.add(note)

            # Maybe issues UPDATE
            user.save()

        return user

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for field in self.fields.values():
    #         field.widget.attrs['class'] = 'form-control'

tsurami/forms.py
from django import forms

from .models import Note, Page

NewNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', ]

NewPageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ['text', ]
    

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

from .forms import UserSignUpForm

class SignUpView(generic.CreateView):
    form_class = UserSignUpForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

tsurami/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from tsurami.models import Note

# TemplateViewを継承したIndexView
class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'tsurami/index.html'

    def get_context_data(self, **kwargs):

        # はじめにPostIndexViewの継承元のメソッドを呼び出す
        context = super().get_context_data(**kwargs)
        context['aaa'] = "from view"
        return context

# LoginRequiredMixinを継承する区間は常にログイン制御が行われる
class MyListView(LoginRequiredMixin, generic.ListView):
    model = Note

    def get_context_data(self, **kwargs):
        # はじめにPostIndexViewの継承元のメソッドを呼び出す
        context = super().get_context_data(**kwargs)
        context['data'] = "data exists"
        if self.model.objects == None:
            context['data'] = "no data"
        else:
            paginate_by = 5

        return context

    def get_queryset(self):
        # ログインユーザの
        # return self.model.objects.filter(user=self.request.user)
        return self.request.user.notes.all()

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Sign up</h1>
<section class="common-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="submit">Sign up</button>
  </form>
</section>
{% endblock %}

tsurami/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'tsurami/css/bootstrap.css' %}" rel="stylesheet">
    <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}Blog App with Auth | Django2 Tutorial</title>
</head>
<body>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <p class="site-name"><a href="{% url 'tsurami:index' %}">Blog App</a></p>
    <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'logout' %}" class="logout">Logout</a></li>
        {% else %}
        <li><a href="{% url 'accounts:signup' %}" class="signup">Sign up</a></li>
        <li><a href="{% url 'login' %}" class="login">Login</a></li>
        {% endif %}
    </ul>
    {% if user.is_authenticated %}
        <a href="{% url 'profile' % }" class="profile">{{ user.username }}さん</a>
    {% endif %}
</nav>

<div class="container">
    <header>
    </header>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

tsurami/templates/tsurami/index.html
{% extends 'base.html' %}

{% block content %}This is {{ aaa }} !!!{% endblock %}

tsurami/templates/tsurami/note_list.html
{% extends 'base.html' %}
{% block title %}Note{% endblock %}

{% block content %}
<ul>
    {{ data }}
    {% for item in object_list %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
{% endblock %}